num_workers: 47

train:
  max_epochs: 100
  batch_size: 64
  lr: 1.0e-5
  weight_decay: 0
  gamma: 0.95
  loss_kwargs:
    alpha: 1.0e+3
    beta: 1
    topk: 0.50

test:
  mc_n: 32
  batch_size: 16

predict:
  metric: "std"
  th: 1.0
  step: 192

model:
  latent_dims: [1,1,1,1]
  in_channels: 3
  num_classes: 4
  num_cuts: 3
