num_workers: 16

train:
  max_epochs: 500
  batch_size: 32
  lr: 1.0e-5
  weight_decay: 0
  T_0: 100
  gamma: 0.5
  T_up: 0
  loss_kwargs:
    type: "elbo"
    kappa: 0.60
    kappa_grade: -0.5
    rate: 1.0e-2
    alpha: 1.0e+3
    beta: 1

test:
  mc_n: 30
  batch_size: 16

predict:
  metric: "std"
  th: 1.0
  step: 192

model:
  latent_dims: [1,1,1,1]
  in_channels: 3
  num_classes: 4
  num_cuts: 3
