num_workers: 16

train:
  max_epochs: 1000
  batch_size: 16
  lr: 1.0e-4
  step_size: 200
  gamma: 0.5
  weight_decay: 1.0e-5
  loss_kwargs:
    type: "geco" # "elbo"
    top_k_percentage: 0.14 # 0.273 # 1 - cohen's kappa
    deterministic_top_k: False
    kappa: 0.10
    decay: 0.99
    rate: 1.0e-2
    beta: 1 # 10

test:
  mc_n: 128
  batch_size: 128

predict:
  metric: "entropy"
  th: 1.0

model:
  latent_dims: [4,1,1,1]
  in_channels: 3
  num_classes: 2
